[package]
name = "ena"
version = "0.2.2"
authors = ["shiimizu <shiimizu@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
lto = true
codegen-units = 1
panic = 'abort'

[dependencies.serde_json]
version = "*"
features = ["preserve_order"]

[dependencies.postgres]
version = "*"
features = ["with-serde_json"]

[dependencies]
serde = "*"
serde_derive = "*"
reqwest = "*"
chrono = "*"
futures = { git = "https://github.com/rust-lang/futures-rs" }
futures-util = "0.3.1"
rand = "*"
pretty_env_logger = "*"
log = "*"
if_chain = "*"
sha2 = { version = "*", features=["std"] }
async-std = { git = 'https://github.com/stjepang/async-std', branch = 'new-scheduler' }
ctrlc = { version = "*", features = ["termination"] }
